url=${LIQUIBASE_URL}
username=${LIQUIBASE_USERNAME}
password=${LIQUIBASE_PASSWORD}
driver=org.postgresql.Driver

changeLogFile=db/changelog/db.changelog-master.yaml

referenceUrl=hibernate:spring:cloud.poesis.itip.web.backend.user?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy